addSbtPlugin("org.scala-js"       % "sbt-scalajs"               % "1.12.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"  % "1.2.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"              % "2.5.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"              % "0.11.1")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"                % "5.9.0")
addSbtPlugin("com.github.cb372"   % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"                 % "1032048a")
addSbtPlugin("com.github.sbt"       % "sbt-ci-release"            % "1.5.11")
