addSbtPlugin("org.scala-js"       % "sbt-scalajs"               % "1.9.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"  % "1.1.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"              % "2.4.6")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"              % "0.9.34")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"                % "5.6.5")
addSbtPlugin("com.github.cb372"   % "sbt-explicit-dependencies" % "0.2.16")
addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"                 % "1.4.13")
addSbtPlugin("com.geirsson"       % "sbt-ci-release"            % "1.5.7")
